/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PitchRouteImport } from './routes/pitch'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppActivityRouteImport } from './routes/_authenticated/app.activity'
import { Route as AuthenticatedAppAssistantRouteImport } from './routes/_authenticated/app.assistant'
import { Route as AuthenticatedAppCardsRouteImport } from './routes/_authenticated/app.cards'
import { Route as AuthenticatedAppLettersRouteImport } from './routes/_authenticated/app.letters'
import { Route as AuthenticatedAppPayRouteImport } from './routes/_authenticated/app.pay'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchRoute = PitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppActivityRoute =
  AuthenticatedAppActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAssistantRoute =
  AuthenticatedAppAssistantRouteImport.update({
    id: '/assistant',
    path: '/assistant',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCardsRoute = AuthenticatedAppCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLettersRoute = AuthenticatedAppLettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPayRoute = AuthenticatedAppPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pitch': typeof PitchRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/activity': typeof AuthenticatedAppActivityRoute
  '/app/assistant': typeof AuthenticatedAppAssistantRoute
  '/app/cards': typeof AuthenticatedAppCardsRoute
  '/app/letters': typeof AuthenticatedAppLettersRoute
  '/app/pay': typeof AuthenticatedAppPayRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pitch': typeof PitchRoute
  '/app/activity': typeof AuthenticatedAppActivityRoute
  '/app/assistant': typeof AuthenticatedAppAssistantRoute
  '/app/cards': typeof AuthenticatedAppCardsRoute
  '/app/letters': typeof AuthenticatedAppLettersRoute
  '/app/pay': typeof AuthenticatedAppPayRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pitch': typeof PitchRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/activity': typeof AuthenticatedAppActivityRoute
  '/_authenticated/app/assistant': typeof AuthenticatedAppAssistantRoute
  '/_authenticated/app/cards': typeof AuthenticatedAppCardsRoute
  '/_authenticated/app/letters': typeof AuthenticatedAppLettersRoute
  '/_authenticated/app/pay': typeof AuthenticatedAppPayRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pitch'
    | '/app'
    | '/app/activity'
    | '/app/assistant'
    | '/app/cards'
    | '/app/letters'
    | '/app/pay'
    | '/app/settings'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pitch'
    | '/app/activity'
    | '/app/assistant'
    | '/app/cards'
    | '/app/letters'
    | '/app/pay'
    | '/app/settings'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pitch'
    | '/_authenticated/app'
    | '/_authenticated/app/activity'
    | '/_authenticated/app/assistant'
    | '/_authenticated/app/cards'
    | '/_authenticated/app/letters'
    | '/_authenticated/app/pay'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PitchRoute: typeof PitchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch': {
      id: '/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof PitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/activity': {
      id: '/_authenticated/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AuthenticatedAppActivityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/assistant': {
      id: '/_authenticated/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AuthenticatedAppAssistantRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cards': {
      id: '/_authenticated/app/cards'
      path: '/cards'
      fullPath: '/app/cards'
      preLoaderRoute: typeof AuthenticatedAppCardsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/letters': {
      id: '/_authenticated/app/letters'
      path: '/letters'
      fullPath: '/app/letters'
      preLoaderRoute: typeof AuthenticatedAppLettersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pay': {
      id: '/_authenticated/app/pay'
      path: '/pay'
      fullPath: '/app/pay'
      preLoaderRoute: typeof AuthenticatedAppPayRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppActivityRoute: typeof AuthenticatedAppActivityRoute
  AuthenticatedAppAssistantRoute: typeof AuthenticatedAppAssistantRoute
  AuthenticatedAppCardsRoute: typeof AuthenticatedAppCardsRoute
  AuthenticatedAppLettersRoute: typeof AuthenticatedAppLettersRoute
  AuthenticatedAppPayRoute: typeof AuthenticatedAppPayRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppActivityRoute: AuthenticatedAppActivityRoute,
  AuthenticatedAppAssistantRoute: AuthenticatedAppAssistantRoute,
  AuthenticatedAppCardsRoute: AuthenticatedAppCardsRoute,
  AuthenticatedAppLettersRoute: AuthenticatedAppLettersRoute,
  AuthenticatedAppPayRoute: AuthenticatedAppPayRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PitchRoute: PitchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
